version: '3.8'

services:
  postgres:
    image: postgres:17-alpine3.20
    environment:
      POSTGRES_DB: "db"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "qwerqwer"
    ports:
      - "9001:5432"
    restart: unless-stopped


